#!/bin/sh
./konjuring -r dero.rabidmining.com:443 -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xm6uavs6msuuaksjcgh22 -m $(nproc --all) -k -1 -ft -1 -report-realtime-hashrate -zero-hr-restart-time
